<script>
import xmlFormat from 'xml-formatter'; 
import { XMLParser , XMLBuilder, XMLValidator } from 'fast-xml-parser'; 

let eventos = {'s2200': `
<?xml version="1.0" encoding="UTF-8"?>
<eSocial xmlns="http://www.esocial.gov.br/schema/evt/evtAdmissao/v_S_01_03_00">
    <evtAdmissao Id="">
        <ideEvento>
			<indRetif></indRetif>
			<nrRecibo></nrRecibo>
			<tpAmb></tpAmb>
			<procEmi></procEmi>
			<verProc></verProc>
        </ideEvento>
        <ideEmpregador>
			<tpInsc></tpInsc>
			<nrInsc></nrInsc>
        </ideEmpregador>
        <trabalhador>
            <cpfTrab></cpfTrab>
            <nmTrab></nmTrab>
            <sexo></sexo>
            <racaCor></racaCor>
            <estCiv></estCiv>
            <grauInstr></grauInstr>
            <nmSoc></nmSoc>
            <nascimento>
                <dtNascto></dtNascto>
                <paisNascto></paisNascto>
                <paisNac></paisNac>
            </nascimento>
            <endereco>
                <brasil>
                    <tpLograd></tpLograd>
                    <dscLograd></dscLograd>
                    <nrLograd></nrLograd>
                    <complemento></complemento>
                    <bairro></bairro>
                    <cep></cep>
                    <codMunic></codMunic>
                    <uf></uf>
                </brasil>
                <exterior>
					<paisResid></paisResid>
					<dscLograd></dscLograd>
					<nrLograd></nrLograd>
					<complemento></complemento>
					<bairro></bairro>
					<nmCid></nmCid>
					<codPostal></codPostal>
                </exterior>
            </endereco>
			<trabImig>
				<tmpResid></tmpResid>
				<condIng></condIng>
			</trabImig>
            <infoDeficiencia>
				<defFisica></defFisica>
				<defVisual></defVisual>
				<defAuditiva></defAuditiva>
				<defMental></defMental>
				<defIntelectual></defIntelectual>
				<reabReadap></reabReadap>
				<infoCota></infoCota>
				<observacao><observacao>
            </infoDeficiencia>
            <dependente> 
                <tpDep></tpDep>
                <nmDep></nmDep>
                <dtNascto></dtNascto>
                <cpfDep></cpfDep>
                <sexoDep></sexoDep>
                <depIRRF></depIRRF>
                <depSF></depSF>
                <incTrab></incTrab>
                <descrDep></descrDep>
            </dependente>
            <contato>
                <fonePrinc></fonePrinc>
                <emailPrinc></emailPrinc>
            </contato>
        </trabalhador>
        <vinculo>
            <matricula></matricula>
            <tpRegTrab></tpRegTrab>
            <tpRegPrev></tpRegPrev>
            <cadIni></cadIni>
            <infoRegimeTrab>
                <infoCeletista>
                    <dtAdm></dtAdm>
                    <tpAdmissao></tpAdmissao>
                    <indAdmissao></indAdmissao>
                    <nrProcTrab></nrProcTrab>
                    <tpRegJor></tpRegJor>
                    <natAtividade></natAtividade>
                    <dtBase></dtBase>
                    <cnpjSindCategProf></cnpjSindCategProf>
                    <matAnotJud></matAnotJud>
                    <FGTS>
                        <dtOpcFGTS></dtOpcFGTS>
                    </FGTS>
                    <trabTemporario>
						<hipLeg></hipLeg>
						<justContr></justContr> 
                        <ideEstabVinc>
							<tpInsc></tpInsc>
							<nrInsc></nrInsc>
						</ideEstabVinc>
                        <ideTrabSubstituido>
							<cpfTrabSubst></cpfTrabSubst>
						</ideTrabSubstituido>
                    </trabTemporario>
                    <aprend>
						<indAprend></indAprend>
						<cnpjEntQual></cnpjEntQual>
						<tpInsc></tpInsc>
						<nrInsc></nrInsc>
						<cnpjPrat></cnpjPrat>
					</aprend> 
                </infoCeletista>
                <infoEstatutario>
					<tpProv></tpProv>
					<dtExercicio></dtExercicio>
					<tpPlanRP></tpPlanRP>
					<indTetoRGPS></indTetoRGPS>
					<indAbonoPerm></indAbonoPerm>
					<dtIniAbono></dtIniAbono>
				</infoEstatutario>
            </infoRegimeTrab>
            <infoContrato>
                <nmCargo></nmCargo>
                <CBOCargo></CBOCargo>
                <dtIngrCargo></dtIngrCargo>
                <nmFuncao></nmFuncao>
                <CBOFuncao></CBOFuncao>
                <acumCargo></acumCargo>
                <codCateg></codCateg>
                <remuneracao>
                    <vrSalFx></vrSalFx>
                    <undSalFixo></undSalFixo>
                    <dscSalVar></dscSalVar>
				</remuneracao>
                <duracao>
                    <tpContr></tpContr>
                    <dtTerm></dtTerm>
                    <clauAssec></clauAssec>
                    <objDet></objDet>
                </duracao>
                <localTrabalho>
                    <localTrabGeral>
                        <tpInsc></tpInsc>
                        <nrInsc></nrInsc>
                        <descComp></descComp>
                    </localTrabGeral>
                    <localTempDom></localTempDom>
                </localTrabalho>
                <horContratual>
                    <qtdHrsSem></qtdHrsSem>
                    <tpJornada></tpJornada>
                    <tmpParc></tmpParc>
                    <horNoturno></horNoturno>
                    <dscJorn></dscJorn>
                </horContratual>
                <alvaraJudicial>
                    <nrProcJud></nrProcJud>
                </alvaraJudicial>
                <observacoes>
                    <observacao></observacao>
                </observacoes>
                <treiCap>
                    <codTreiCap></codTreiCap>
                </treiCap>
                <sucessaoVinc>
                    <tpInsc></tpInsc>
                    <nrInsc></nrInsc>
                    <matricAnt></matricAnt>
                    <dtTransf></dtTransf>
                    <observacao></observacao>
                </sucessaoVinc>
            </infoContrato>
            <sucessaoVinc>
				<tpInsc></tpInsc>
				<nrInsc></nrInsc>
				<matricAnt></matricAnt>
				<dtTransf></dtTransf>
				<observacao></observacao>
			</sucessaoVinc>
            <transfDom>
				<cpfSubstituido></cpfSubstituido>
				<matricAnt></matricAnt>
				<dtTransf></dtTransf>
			</transfDom>
            <mudancaCPF>
				<cpfAnt></cpfAnt>
				<matricAnt></matricAnt>
				<dtAltCPF></dtAltCPF>
				<observacao></observacao>
			</mudancaCPF>
            <afastamento>
                <dtIniAfast></dtIniAfast>
                <codMotAfast></codMotAfast>
            </afastamento>
            <desligamento>
                <dtDeslig></dtDeslig>
            </desligamento>
            <cessao> 
                <dtIniCessao></dtIniCessao>
            </cessao>
        </vinculo>
    </evtAdmissao>
</eSocial>`, }


//let formattedXML = xmlFormat(eventos.s2200)
//console.log(formattedXML)

const parser = new XMLParser(); 
let jsonObj = parser.parse(eventos.s2200); 
console.log(jsonObj); 
</script>